site_name: Kedro Aim
site_description: "A kedro plugin that enables logging to the ml experiment tracker aim"
copyright: Made with ❤️ by An Hoang
use_directory_urls: false
repo_url: https://github.com/AnH0ang/kedro-aim
repo_name: AnH0ang/kedro-aim

theme:
  name: material
  # favicon: assets/logo.png
  # logo: assets/logo.png
  palette:
    - schema: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - content.code.annotate
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

extra_css:
  - assets/css/mkdocstrings.css

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AnHo4ng
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/anh0ang

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

watch:
  - src

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: yes
            merge_init_into_class: false
            show_source: true
            show_root_heading: false
            show_root_toc_entry: false
            show_submodules: true
            show_object_full_path: true
nav:
  - Home: index.md
  - Usage: logic/usage.md
  - Configuration: logic/configuration.md
  - Developement: logic/developement.md
  - API Reference:
      - kedro_aim.aim: code/aim.md
      - kedro_aim.config: code/config.md
      - kedro_aim.io: code/io.md
      - kedro_aim.framework.cli: code/cli.md
      - kedro_aim.framework.hooks: code/hooks.md
  - Changelog: logic/changelog.md
