name: Validate PR Title
on:
  pull_request_target:
    types: [opened, edited]

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install commitizen
        run: pip install -Uq commitizen
      - name: Check title with commitizen
        run: pip install -Uq commitizen
      - name: Label pull request
        run: cz check -m "${{ github.event.pull_request.title }}"
