name: Code Quality

on:
  pull_request:
    paths-ignore:
      - docs/**
  push:
    paths-ignore:
      - docs/**
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    name: Linting
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.11
      - run: pip install click==8.0.0
      - uses: pre-commit/action@v2.0.3
        env:
          SKIP: generate_json_schema
