name: Publish Package to PyPI

on:
  push:
    tags:
      - "*"

jobs:
  bump-version:
    runs-on: ubuntu-latest
    name: Publish Package in PyPI
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python 3.8.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.8.11

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3.0.1
        with:
          path: .venv
          key: venv-${{ runner.python-version }}-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Install library
        run: poetry install --no-interaction

      - name: Build
        run: |
          poetry build
          poetry publish --username __token__ --password ${{ secrets.PYPI_PASSWORD }}
