name: Release Pipeline

on:
  push:
    branches:
    - master
    - main

jobs:
  bump-version:
    if: "!startswith(github.event.head_commit.message, 'bump:') || !startswith(github.event.head_commit.message, 'Bump')"
    runs-on: ubuntu-latest
    name: Bump version and create changelog with commitizen
    steps:
    - name: Check out
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Create bump and changelog
      uses: commitizen-tools/commitizen-action@master
      with:
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        changelog_increment_filename: body.md

    - name: Set up Python 3.9.11
      uses: actions/setup-python@v3
      with:
        python-version: 3.9.11

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Load cached venv
      id: cached-poetry-dependencies
      uses: actions/cache@v3.0.1
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-root

    - name: Install library
      run: poetry install --no-interaction

    - name: Build
      run: |
        poetry build
       # poetry publish --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }}

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: dist/*
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        draft: false
        prerelease: steps.check-version.outputs.prerelease == 'true'
        bodyFile: body.md
        tag: ${{ env.REVISION }}
